### ISSUE TITLE
process: absolute links in interactive-examples

### ISSUE THREAD

**Issue by myfreeer** [myfreeer/mdn-local#31]
Example page:
https://developer.mozilla.org/zh-CN/docs/Web/CSS/background-position

Example iframe:
https://interactive-examples.mdn.mozilla.net/pages/css/background-position.html

Resource src:
https://interactive-examples.mdn.mozilla.net/live-examples/css-examples/backgrounds-and-borders/background-position.css

```css
#example-element {
    background-color: #ffdead;
    background-image: url(/media/examples/star.png);
    background-repeat: no-repeat;
    height: 100%
}
```
